export const FETCH_Add_CARTITEM ='Add_CARTITEM';
export const FETCH_REMOVE_CARTITEM ='REMOVE_CARTITEM';
export const FETCH_INCREMENT_CARTITEM ='INCREMENT_CARTITEM';
export const FETCH_DECREMENT_CARTITEM ='DECREMENT_CARTITEM';
export const POST_CONTACT = 'POST_CONTACT';
