export const FETCH_MAIN_LOADING = 'FETCH_MAIN_LOADING';
export const FETCH_MAIN_DATA = 'FETCH_MAIN_DATA';
export const FETCH_MAIN_FAILED = 'FETCH_MAIN_FAILED';

export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_DATA = 'FETCH_CATEGORY_DATA';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';

export const FETCH_ITEMS_LOADING = 'FETCH_ITEMS_LOADING';
export const FETCH_ITEMS_DATA = 'FETCH_ITEMS_DATA';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';

export const FETCH_CART_LOADING = 'FETCH_CART_LOADING';
export const FETCH_CART_DATA = 'FETCH_CART_DATA';
export const FETCH_CART_FAILED = 'ETCH_CART_FAILED';