export const Add_CARTITEM ='Add_CARTITEM';
export const REMOVE_CARTITEM ='REMOVE_CARTITEM';
export const INCREMENT_CARTITEM ='INCREMENT_CARTITEM';
export const DECREMENT_CARTITEM ='DECREMENT_CARTITEM';
export const GET_CARTITEM = 'GET_CARITEM';
